Traceback (most recent call last):
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork_mp.py", line 72, in contactnetwork_worker
    contact_network_util.simulate_contact_network(day, weekday)
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork.py", line 77, in simulate_contact_network
    cell_agents_directcontacts, cell = self.simulate_contact_network_by_cellid(cellid, day)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork.py", line 104, in simulate_contact_network_by_cellid
    agents_directcontacts, cell = self.generate_contact_network(cellid)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork.py", line 122, in generate_contact_network
    cell = self.cells[cellid]
           ~~~~~~~~~~^^^^^^^^
  File "<string>", line 2, in __getitem__
  File "C:\Program Files\Python3112\Lib\multiprocessing\managers.py", line 837, in _callmethod
    raise convert_to_error(kind, result)
KeyError: -1
