Traceback (most recent call last):
  File "C:\AppsPy\mtdcovabm\simulator\sim.py", line 382, in <module>
    itinerary_util.generate_local_itinerary(day, weekday, agents_ids_by_ages, hh_inst["resident_uids"])
  File "c:\AppsPy\mtdcovabm\simulator\itinerary.py", line 415, in generate_local_itinerary
    for timestep, (action, _) in agent["itinerary"].items():
                                 ~~~~~^^^^^^^^^^^^^
KeyError: 'itinerary'
